annotations:
  category: ApplicationServer
apiVersion: v2
dependencies:
- name: app
  repository: oci://trialoppsko.jfrog.io/app01
  tags:
  - bitnami-common
  version: 0.1.0
description: A helm chart for deploying Python web and backend applications
home: https://www.leadbook.com
maintainers:
- email: cto@leadbook.com
  name: Leadbook
name: app
sources:
- https://github.com/VentesWorks/
version: 0.1.0
