app: 
# all components of the release (create one deployment for each)
# the first component is the main component
# if the app is a service, the main component is the server component
  components:
    - name: main
      image:
        registry: docker.io
        repository: jabzta84/flaskapp
        tag: latestv4

        pullPolicy: IfNotPresent
        pullSecrets: []
      replicaCount: 2

    
